export interface CartInterface {
    consumer_name?: string,
    prouduct_name?: string,
    total_cost?: number,
    id_product?: string,
    id_shop?: string,
    status_transaction: string,
    consumer_address?: string,
    shop_name?: string,
    seller_address?: string,
    quantity?: number,
    size_prouduct?: number,
    color_prouduct?: string,
    category_product?: string,
    date_buy?: Date,
    consumer_email?: string,
    seller_email?: string,
    consumer_telephone?: string,
    seller_telephone?: string
}