export interface CartInterface {
    consumer_name?: string,
    product_name?: string,
    product_price?: number,
    total_cost?: number,
    product_id?: string,
    shop_id?: string,
    shop_name?: string,
    quantity?: number,
    product_size?: number,
    product_color?: string,
    product_brand?: string,
    product_description?: string,
    product_type?: string,
    product_image?: string,
    product_category?: string,
    date_buy?: Date,
    email_consumer?: string,
    image_shop?: string,
    __v?: string,
    _id?: string
}